language: node_js
node_js:
  - 12
dist: bionic

cache:
  directories:
    - "node_modules"

script:
  - yarn build  # Build the SPA

deploy:
  provider: pages
  target-branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard.
  on:
    branch: master
  local_dir: dist
  fqdn: ubacm.org
